[profile.default]
gas_reports = ["*"]
libs = ["lib", "node_modules"]
out = "out"
scripts = 'scripts'
auto_detect_solc = true
solc_version = "0.8.30"
src = "src"
test = "tests/"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
remappings= [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
]

[profile.sepolia]


[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
local = "${LOCAL_RPC_URL}"
porcini = "${PORCINI_RPC_URL}"
root = "${ROOT_RPC_URL}"

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
single_line_statement_blocks = "single"
tab_width = 2
wrap_comments = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
